FROM node:24-alpine AS builder

WORKDIR /api
ENV NODE_ENV='docker'

COPY ../../package.json ../../package-lock.json ./
COPY ../../nest-cli.json ./
COPY ../../tsconfig.json ./
COPY ../../types.d.ts ./

RUN npm install

COPY ../../apps/api-gateway ./apps/api-gateway
COPY ../../apps/share ./apps/share
COPY ../generated ./generated

RUN npm run build api

# ---- Production Stage ----
FROM node:24-alpine

WORKDIR /api
COPY package*.json ./
ENV NODE_ENV='docker'

RUN npm ci --only=production
COPY --from=builder /api/dist/apps/api-gateway ./dist/apps/api-gateway
COPY ../assets ./assets

EXPOSE 5000

CMD ["node", "dist/apps/api-gateway/main"]
