FROM node:24-alpine

WORKDIR /api

COPY ../../package.json ../../package-lock.json ./

RUN npm ci

COPY ../../prisma ./prisma
COPY ../../prisma-config ./prisma-config
COPY ../../init-scripts ./init-scripts
COPY ../../scripts ./scripts

CMD ["sh", "-c", "npm run db:deploy && npm run db:create-user"]
