ARG MODULE_NAME

FROM node:24-alpine AS builder

WORKDIR /api

ARG MODULE_NAME
ENV NODE_ENV='docker'

COPY ../../package.json ../../package-lock.json ./
COPY ../../nest-cli.json ./
COPY ../../tsconfig.json ./
COPY ../../types.d.ts ./

RUN npm install

COPY ../../apps/modules/${MODULE_NAME} ./apps/modules/${MODULE_NAME}
COPY ../../apps/share ./apps/share
COPY ../generated ./generated

RUN npm run build $MODULE_NAME

# ---- Production Stage ----
FROM node:24-alpine

WORKDIR /api
ARG MODULE_NAME
ENV NAME=$MODULE_NAME
ENV NODE_ENV='docker'
COPY package*.json ./

RUN npm ci --only=production
COPY --from=builder /api/dist/apps/modules/${MODULE_NAME} ./dist/apps/modules/${MODULE_NAME}
COPY ../assets ./assets

CMD ["sh", "-c", "node dist/apps/modules/${NAME}/main"]