FROM node:24-alpine

WORKDIR /api

ARG COMMAND
ENV EXECUTE_COMMAND=$COMMAND

COPY ../../package.json ../../package-lock.json ./

RUN npm ci

COPY ../../prisma ./prisma
COPY ../../prisma-config ./prisma-config
COPY ../../init-scripts ./init-scripts
COPY ../../scripts ./scripts

CMD ["sh", "-c", "${EXECUTE_COMMAND} && npm run db:create-user"]
