export const PRODUCT_SERVICE = Symbol('PRODUCT_SERVICE');
export const CATEGORY_SERVICE = Symbol('CATEGORY_SERVICE');
export const PRISMA_CLIENT = Symbol('PRISMA_CLIENT');
export const REDIS_CLIENT = Symbol('REDIS_CLIENT');
export const TECH_SHOP_PG_CONNECTOR = Symbol('TECH_SHOP_PG_CONNECTOR');
export const EVENT_SOURCE_PG_CONNECTOR = Symbol('EVENT_SOURCE_PG_CONNECTOR');
export const EVENT_SOURCE_BULLMQ = 'EVENT_SOURCE_BULLMQ';
