x-shared-env: &shared-env
  DATABASE_URL: postgresql://postgres:${USER}@db:5432/tech-shop?schema=public
  DATABASE_URL_REPLICA_ADMIN: postgresql://tech_shop_admin:${USER}@db:5432/tech-shop?schema=admin
  DATABASE_URL_REPLICA_CUSTOMER: postgresql://tech_shop_customer:${USER}@db:5432/tech-shop?schema=customer
  DATABASE_URL_REPLICA_EMPLOYEE: postgresql://tech_shop_employee:${USER}@db:5432/tech-shop?schema=employee
  EVENT_SOURCE_DATABASE_URL: postgresql://postgres:${USER}@db:5432/event-source?schema=${SCHEMA_NAME}

x-base-microservice: &base-microservice
  environment:
    <<: *shared-env
    REDIS_SERVER_HOST: redis-storage
    BULLMQ_SERVER_HOST: redis-bullmq
    BULLMQ_SERVER_PORT: 6381
  links:
    - redis-storage
    - redis-bullmq
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on:
    prisma-tech-shop:
      condition: service_started
    redis-storage:
      condition: service_healthy
    redis-bullmq:
      condition: service_healthy

services:
  redis-storage:
    image: redis/redis-stack:latest
    container_name: redis-storage
    ports:
      - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
      - 8001:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      retries: 3

  redis-bullmq:
    image: redis/redis-stack:latest
    container_name: redis-bullmq
    ports:
      - 6381:${REDIS_SERVER_PORT}
      - 8000:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      timeout: 5s
      retries: 3

  db:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tech-shop
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prisma-tech-shop:
    build:
      context: .
      dockerfile: ./dockerfile/dockerfile.prisma
    container_name: prisma-tech-shop
    tty: true
    env_file:
      - .env
    environment:
      <<: *shared-env
    ports:
      - 8888:8888
    depends_on:
      db:
        condition: service_healthy

  category:
    <<: *base-microservice
    build:
      context: .
      dockerfile: ./dockerfile/dockerfile.module
      args:
        MODULE_NAME: category
    container_name: category_c
    ports:
      - ${CATEGORY_MICROSERVICE_TCP_PORT}:${CATEGORY_MICROSERVICE_TCP_PORT}
    env_file:
      - .env

  api-gateway:
    build:
      context: .
      dockerfile: ./dockerfile/dockerfile.gateway
    container_name: api_c
    env_file:
      - .env
    <<: *base-microservice
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - category
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${LOCALHOST}:${API_PORT}/healthy/"]
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  api-gateway: